version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  app:
    build: .
    labels:
      - traefik.backend=flw
      - traefik.frontend.rule=Host:flw.lipsumar.io
      - traefik.docker.network=proxy
      - traefik.port=3005
      - traefik.enable=true
    networks:
      - proxy
      - internal
